[project]
name = "crabby"
version = "0.1.0"
description = "Your AI-powered personal assistant designed to automate tasks and simplify your daily life."
authors = [
    {name = "Carlos Padilla Labella",email = "cpadlab@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14,<3.16"
dependencies = [
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "pyqt6 (>=6.11.0,<7.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "pythonnet (>=3.2.0)",
    "pywebview (>=6.2.1,<7.0.0)",
    "ollama (>=0.6.3,<0.7.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
